version: '3.8'
name: docagent-dev
services:
  web:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    volumes:
      - ../source:/app/source
      - ../logs:/app/logs
      - ../alembic:/app/alembic
      - ../data:/app/data
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATA_PATH=/app/data
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
