"""initial migration

Revision ID: 125dc4283bad
Revises: 
Create Date: 2025-06-06 16:13:40.961832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125dc4283bad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='название модели'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='системный промпт'),
    sa.Column('final_prompt', sa.Text(), nullable=True, comment='финальный промпт'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_configs_id'), 'llm_configs', ['id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_from_human', sa.Text(), nullable=True, comment='сообщение от пользователя'),
    sa.Column('message_from_ai_agent', sa.Text(), nullable=True, comment='ответ от llm agent'),
    sa.Column('llm_config_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='время создания записи'),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_llm_configs_id'), table_name='llm_configs')
    op.drop_table('llm_configs')
    # ### end Alembic commands ###
