"""add uuid for chats

Revision ID: de2ee7fdd59a
Revises: 125dc4283bad
Create Date: 2025-06-07 07:47:57.857442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de2ee7fdd59a'
down_revision: Union[str, None] = '125dc4283bad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем новое поле
    op.add_column('chats', sa.Column('chat_id_uuid', sa.UUID(), nullable=True, comment='uuid чата'))
    # Затем удаляем внешний ключ
    op.drop_constraint(op.f('chats_llm_config_id_fkey'), 'chats', type_='foreignkey')
    # Удаляем поле с внешним ключом
    op.drop_column('chats', 'llm_config_id')
    # Теперь можно удалить индекс и саму таблицу
    op.drop_index(op.f('ix_llm_configs_id'), table_name='llm_configs')
    op.drop_table('llm_configs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала создаем таблицу и индекс
    op.create_table('llm_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='название модели'),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=True, comment='системный промпт'),
    sa.Column('final_prompt', sa.TEXT(), autoincrement=False, nullable=True, comment='финальный промпт'),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('llm_configs_pkey'))
    )
    op.create_index(op.f('ix_llm_configs_id'), 'llm_configs', ['id'], unique=False)
    # Затем добавляем поле и внешний ключ
    op.add_column('chats', sa.Column('llm_config_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chats_llm_config_id_fkey'), 'chats', 'llm_configs', ['llm_config_id'], ['id'])
    # В конце удаляем новое поле
    op.drop_column('chats', 'chat_id_uuid')
    # ### end Alembic commands ###
