"""add message_intent column

Revision ID: e241f1b0d4a9
Revises: de2ee7fdd59a
Create Date: 2025-06-09 16:08:15.198630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e241f1b0d4a9'
down_revision: Union[str, None] = 'de2ee7fdd59a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('message_intent', sa.Text(), nullable=True, comment='интент от llm agent'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'message_intent')
    # ### end Alembic commands ###
